version: "3"
services:
  mariadb:
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: "erod_database"
      MYSQL_PASSWORD: "erod_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "erod_user"
    expose:
      - "3306"
    image: "mariadb"
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
  nginx:
    command: "/bin/sh -c \"envsubst '$$RAILS_HOST $$RAILS_ROOT $$SERVER_NAME' < /var/www/app/docker/nginx/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
    environment:
      RAILS_HOST: "rails"
      RAILS_ROOT: "/var/www/app"
      SERVER_NAME: "localhost"
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/app"
  rails:
    build:
      args:
        GEMFILE: "Gemfile"
        GEMFILE_LOCK: "Gemfile.lock"
      context: "./"
      dockerfile: "./docker/rails/Dockerfile"
    command: "puma -w 4"
    environment:
      DOCKERIZE_HOSTS: "mariadb:3306"
      RAILS_DATABASE: "erod_database"
      RAILS_DATABASE_HOST: "mariadb"
      RAILS_DATABASE_PASSWORD: "erod_password"
      RAILS_DATABASE_USERNAME: "erod_user"
      RAILS_ENV: "production"
      RAILS_ROOT: "/var/www/app"
    expose:
      - "3000"
    image: "erod-rails"
    volumes:
      - "./:/var/www/app"
