version: "3"
services:
  mariadb:
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    expose:
      - "3306"
    image: "mariadb"
  rails:
    build:
      args:
        GEMFILE: "Gemfile"
        GEMFILE_LOCK: "Gemfile.lock"
      context: "./"
      dockerfile: "./docker/rails/Dockerfile"
    environment:
      DOCKERIZE_HOSTS: "mariadb:3306"
      RAILS_DATABASE_HOST: "mariadb"
      RAILS_DATABASE_PASSWORD: "password"
      RAILS_DATABASE_USERNAME: "root"
      RAILS_ROOT: "/var/www/app"
    image: "erod-rails"
    ports:
      - "3000:3000"
    volumes:
      - "./:/var/www/app"
