version: "3"
services:
  app:
    build: "./docker/rails"
    environment:
      EROD_BUNDLE_PATH: "/var/www/docker/vendor/bundle"
      EROD_DOCKERIZE_HOSTS: "db:3306"
      EROD_RAILS_ROOT: "/var/www/app"
      RAILS_DATABASE_PASSWORD: "password"
      RAILS_DATABASE_USERNAME: "root"
    image: "erod-rails"
    ports:
      - "3000:3000"
    volumes:
      - "./app:/var/www/app"
      - "./docker/rails:/var/www/docker"
  db:
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    expose:
      - "3306"
    image: "mariadb"
