version: "3"
services:
  app:
    build: "./docker/app"
    environment:
      EROD_APP_ROOT: "/var/www/app"
      EROD_APP_TASKS: "db:create db:migrate db:seed"
      EROD_BUNDLE_PATH: "/var/www/docker/app/vendor/bundle"
      EROD_DOCKERIZE_HOSTS: "db:3306"
      RAILS_DATABASE_PASSWORD: "password"
      RAILS_DATABASE_USERNAME: "root"
    image: "erod-app"
    ports:
      - "3000:3000"
    volumes:
      - "./app:/var/www/app"
      - "./data/app:/var/www/data/app"
      - "./docker/app:/var/www/docker/app"
  db:
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    expose:
      - "3306"
    image: "mariadb"
