version: "3"
services:
  app:
    build: "./docker/rails"
    command: "puma -w 4"
    environment:
      EROD_BUNDLE_PATH: "/var/www/docker/vendor/bundle"
      EROD_DOCKERIZE_HOSTS: "db:3306"
      EROD_RAILS_ROOT: "/var/www/app"
      RAILS_DATABASE: "erod_database"
      RAILS_DATABASE_PASSWORD: "erod_password"
      RAILS_DATABASE_USERNAME: "erod_user"
      RAILS_ENV: "production"
    expose:
      - "3000"
    image: "erod-rails"
    volumes:
      - "./app:/var/www/app"
      - "./docker/rails:/var/www/docker"
  db:
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: "erod_database"
      MYSQL_PASSWORD: "erod_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "erod_user"
    expose:
      - "3306"
    image: "mariadb"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
  web:
    command: "/bin/sh -c \"envsubst '$$EROD_NGINX_LOG $$EROD_NGINX_ROOT $$EROD_NGINX_SERVER' < /var/www/data/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
    environment:
      EROD_NGINX_LOG: "/var/www/data"
      EROD_NGINX_ROOT: "/var/www/app/public"
      EROD_NGINX_SERVER: "listen 80; server_name localhost;"
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./app:/var/www/app"
      - "./data/nginx:/var/www/data"
