version: "3"
services:
  app:
    build: "./docker/app"
    command: "puma -w 4"
    environment:
      EROD_APP_ROOT: "/var/www/app"
      EROD_BUNDLE_PATH: "/var/www/docker/app/vendor/bundle"
      EROD_DOCKERIZE_HOSTS: "db:3306"
      RAILS_DATABASE: "erod_database"
      RAILS_DATABASE_PASSWORD: "erod_password"
      RAILS_DATABASE_USERNAME: "erod_user"
      RAILS_ENV: "production"
    expose:
      - "3000"
    image: "erod-rails"
    volumes:
      - "./app:/var/www/app"
      - "./data/app:/var/www/data/app"
      - "./docker/app:/var/www/docker/app"
  db:
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: "erod_database"
      MYSQL_PASSWORD: "erod_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "erod_user"
    expose:
      - "3306"
    image: "mariadb"
    volumes:
      - "./data/db:/var/lib/mysql"
  web:
    command: "/bin/sh -c \"envsubst '$$EROD_WEB_LOG $$EROD_WEB_ROOT $$EROD_WEB_SERVER' < /var/www/data/web/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
    environment:
      EROD_WEB_LOG: "/var/www/data/web"
      EROD_WEB_ROOT: "/var/www/app/public"
      EROD_WEB_SERVER: "listen 80; server_name localhost;"
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./app:/var/www/app"
      - "./data/web:/var/www/data/web"
